<a href="https://colab.research.google.com/github/pravincoder/Fundamentals_tensorflow/blob/main/Complete_tenors_tutorial_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed

# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
import tensorflow as tf




# **TensorFlow and Deep Learning Fundamentals(Zero to Hero)**

# **Part 1 - Tensor's**

# **Step 1**:- Creating our first tensors with TensorFlow

**What is tensor in simple words?**

**Tensors are simply mathematical objects that can be used to describe physical properties, just like scalars and vectors. In fact tensors are merely a generalisation of scalars and vectors; a scalar is a zero rank tensor, and a vector is a first rank tensor.**

![Tensor](https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Components_stress_tensor.svg/1200px-Components_stress_tensor.svg.png)

In [2]:
#Tensor (Variable & Constant)
changeable_tensor = tf.Variable([5,5])
unchangeable_tensor=tf.constant([5,5])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>)

In [3]:
# Try changing one element in 'changeable_tensor'
changeable_tensor[1].assign(7)
# changeable_tensor[0]=7 (error)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

# **Step 2:-** Creating Random Tensor

**Random tensor are tensor of some arbitary size which contain random number

In [4]:
# Random Tensor
random_1 = tf.random.Generator.from_seed(42) # Set seed for reproducibility
random_1 = random_1.uniform(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2=random_2.uniform(shape=(3,2))
random_1,random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle order of tensor

**More info on  [Random Shuffle](https://www.tensorflow.org/api_docs/python/tf/random/shuffle)**

In [5]:
#Shuffle a Tensor (used when you want to shuffle your data to inherint order doesn't effect learning ) 
not_shuffled = tf.constant([[10,7],
                           [3,5],
                           [2,8]])
not_shuffled.ndim

2

In [6]:
# Shuffle our non_shuffled Tensor
seed = tf.random.set_seed(42) #Global level random seed
tf.random.shuffle(not_shuffled,seed)

# Shuffled in order of first dim(10,3,2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 2,  8],
       [10,  7]], dtype=int32)>

In [7]:
tf.random.shuffle(not_shuffled,seed=42) #Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 2,  8]], dtype=int32)>

 > ## Note:- If we want our tensors to be in same order we must use **GLobal level random seed** and for random order each time we use  **Operation level random seed.**

## Other ways to make tensor 
>### 1. `tf.ones` ,`tf.zeros` (same as numpy.ones)

>### 2. Numpy arrays into Tensors
   #### **Additional info :-** The major difference in Numpy array and tensorflow Tensor is that tensor can be run on GPU. (Fast Computation)  


In [8]:
tf.ones([5,5],tf.int32)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [9]:
# Create a tensor of all zeroes
tf.zeros([5,8])

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [10]:
# Convert numpy array into tensor
numpy_1 = np.arange(1,25,dtype=np.int32) # Creates a numpy array btw 1 & 25
numpy_1
#X = tf.constant(some_matix) #Capital (X) for matrix or Tensor
#y = tf.constant(vector) # non-capital for vector
A = tf.constant(numpy_1,shape=(2,3,4)) # tensor (more than one dimension)
B = tf.constant(numpy_1) # vector (one dimension)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

## Getting information from tensor

## Attribute to keep in mind when dealing with tensor:-
* ### shape `array.shape`
* ### Rank  `array.ndim`
* ### Axis/Dimension `array[axis_count]`
* ### Size `tf.size(array)`

In [11]:
# Task :- Create a rank 4 tensor with all value inside as 0 (4 dimensions)
rank_4 = tf.zeros(shape=(3,2,3,2))
rank_4

<tf.Tensor: shape=(3, 2, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [12]:
rank_4[0] # get first(zeroth) element same as a list in python
# recheck the change in shape below 

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

In [13]:
rank_4.shape # Shape

TensorShape([3, 2, 3, 2])

In [14]:
rank_4.ndim      # Rank(No. of dimensions)

4

In [15]:
tf.size(rank_4)      #Size (3*2*3*2)=36

<tf.Tensor: shape=(), dtype=int32, numpy=36>

In [16]:
rank_4[0]     #Axis

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

In [17]:
# Get other Attributes of Tensor
 
def get_tensor_info(A):
    print("DataType of every element: ",A.dtype)
    print("Number of dimension(rank): ",A.ndim)
    print("Shape of tensor: ",A.shape)
    print("Element along the 0 axies: ",A.shape[0])
    print("Element along the last axis: ",A.shape[-1])
    print("Total number of elements in tensor: ",tf.size(A))
    print("Total number of elements in tensor: ",tf.size(A).numpy())


In [18]:
get_tensor_info(rank_4)

DataType of every element:  <dtype: 'float32'>
Number of dimension(rank):  4
Shape of tensor:  (3, 2, 3, 2)
Element along the 0 axies:  3
Element along the last axis:  2
Total number of elements in tensor:  tf.Tensor(36, shape=(), dtype=int32)
Total number of elements in tensor:  36


## Indexing Tensor `array[X]`
### Tensor can be indexed just like Python list


In [19]:
# Get the first 2 element of each dimension
rank_4[:1,:2,]

<tf.Tensor: shape=(1, 2, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [20]:
# Get the first element of each dimension except the last one
rank_4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[0., 0.]]]], dtype=float32)>

In [21]:
# Create a new rank_2 (2 dim tensor)
rank_2 = tf.constant([[1,2],[3,4]])
rank_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [22]:
rank_2.ndim

2

In [23]:
# get last item of each of row of our rank 2 tensor
rank_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [24]:
# Add extra dimension to rank 2 tensor
rank_3 = rank_2[...,tf.newaxis] # Alterantive = rank_2[:,:,tf.newaxis]

rank_3 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [25]:
rank_3.ndim

3

In [26]:
# Alternative of newaxis is expand_dim
tf.expand_dims(rank_2,axis=-1) # can add dimension in middle as well  
rank_3+10

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[11],
        [12]],

       [[13],
        [14]]], dtype=int32)>

In [27]:
# Original tensor is not change With +10 
rank_3 # the main tensor doesn't change until we set it ! like rank_3 = rank_3+10
# also support other operation like -,*,/ etc


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [28]:
# alternative of math operation is build-in-function
tf.multiply(rank_3,5) # same as rank_3 * 5

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 5],
        [10]],

       [[15],
        [20]]], dtype=int32)>

## Matrix/Tensor Multiplication (IMP) `@` , `tf.matmul`, `tf.tensordot()` .
### In Machine learning ,multiplication is one of the most common tensor operations.(tensor*tensor)

### **Dot Product** Rule :- The Colm of matrix A should be equal to the row of matrix B and wise-versa

> ###  Resource for Matrix Multiplication :-https://www.mathsisfun.com/algebra/matrix-multiplying.html 
> ### For visualization visit :- https://nathancarter.github.io/matrix-mult/


In [29]:
# Matrix Multiplication in tf
print(rank_2)
tf.matmul(rank_2,rank_2) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [30]:
rank_2 * rank_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [31]:
# Matrix Multiplication with python operator
print(rank_2)
print(rank_3)
rank_2 @ rank_3

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 5],
        [11]],

       [[11],
        [25]]], dtype=int32)>

In [32]:
# create matrix with shape (3,2)
X = tf.constant([[1,2],[3,4],[5,6]])
# create matrix with shape(2,3)
Y = tf.constant([[1,2,3],[4,5,6]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [33]:
# check if multiplication of X and Y is possible or not
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [34]:
# Multipication using reshape
tf.matmul(tf.reshape(Y,shape=(2,3)) , tf.reshape(X,shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [35]:
# Multipication using transpose
tf.matmul(tf.transpose(X),tf.transpose(Y))

# Transpose != reshape

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 49],
       [28, 64]], dtype=int32)>

In [36]:
# Using tensordot(tensor contration)
tf.tensordot(X,Y,axes=1) # same as X @ Y,tf.matmul(X,Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

## Change Data Type of tensor `dtype`

In [37]:
#  The default datatype depends on the datatype of the Tensor you input
# Example
A = tf.constant([[1,2],[3,2]])
B = tf.constant([1.2,1.4])
A.dtype,B.dtype
# here default precision is 32bit

(tf.int32, tf.float32)

In [38]:
# use 8,16,32,64... depending on memory and process
#Reduce precision (32--> 16)
tf.cast(A,dtype=tf.int16)
#similarly even increase precision 

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 2]], dtype=int16)>

## Aggregating Tensor
### Aggregating Tensor = condensing them from multiple value down to samller amount of values

In [39]:
# Get absolute value
S = tf.constant([-1,-2,4])
tf.abs(S)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4], dtype=int32)>

## *Practice :-* Create a function to get the following aggregations -
* ###  Minimum of the Tensor
* ###  Maximum of the Tensor
* ###  Get the mean of the Tensor
* ###  Get the sum of Tensor

In [40]:
def aggr(tensor):
    min = tf.reduce_min(tensor)
    max = tf.reduce_max(tensor)
    mean = tf.reduce_mean(tensor)
    sum = tf.reduce_sum(tensor)
    print("min: ",min.numpy())  
    print("max: ",max.numpy())
    print("mean: ",mean.numpy())
    print("sum: ",sum.numpy())


aggr(A)

min:  1
max:  3
mean:  2
sum:  8


## Find the positional Maximum and Minimum

In [41]:
# creating a random tensor
tf.random.set_seed(35)
R = tf.random.uniform(shape=[30])
R

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.08097744, 0.27146375, 0.26112723, 0.39334738, 0.7670845 ,
       0.5373272 , 0.53815246, 0.41563308, 0.40667117, 0.65529   ,
       0.5291939 , 0.13502538, 0.59320295, 0.5388031 , 0.17635989,
       0.45555162, 0.9611225 , 0.7442961 , 0.77252376, 0.6969732 ,
       0.57887435, 0.74274695, 0.25819337, 0.2897116 , 0.10989571,
       0.6813458 , 0.7710763 , 0.7605777 , 0.5021825 , 0.03790379],
      dtype=float32)>

In [42]:
# Find the positional maximum
tf.argmax(R)


<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [43]:
# Max Value is 
R[int(tf.argmax(R).numpy())].numpy()

0.9611225

In [44]:
# find Positional Min
tf.argmin(R)

<tf.Tensor: shape=(), dtype=int64, numpy=29>

In [45]:
# Min value is 
R[int(tf.argmin(R).numpy())].numpy()

0.037903786

## Editing dimension of a tensor(Squeezing Tensor)

In [46]:
# Using the previous tensor 'R' but ReShaping it
RR = tf.reshape(R, shape=[1,1,1,1,30])
RR,RR.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 30), dtype=float32, numpy=
 array([[[[[0.08097744, 0.27146375, 0.26112723, 0.39334738, 0.7670845 ,
            0.5373272 , 0.53815246, 0.41563308, 0.40667117, 0.65529   ,
            0.5291939 , 0.13502538, 0.59320295, 0.5388031 , 0.17635989,
            0.45555162, 0.9611225 , 0.7442961 , 0.77252376, 0.6969732 ,
            0.57887435, 0.74274695, 0.25819337, 0.2897116 , 0.10989571,
            0.6813458 , 0.7710763 , 0.7605777 , 0.5021825 , 0.03790379]]]]],
       dtype=float32)>, TensorShape([1, 1, 1, 1, 30]))

In [47]:
# Squeezing = Remove dim of size 1 from the tensor
RR_s = tf.squeeze(RR)
RR_s,RR_s.shape

(<tf.Tensor: shape=(30,), dtype=float32, numpy=
 array([0.08097744, 0.27146375, 0.26112723, 0.39334738, 0.7670845 ,
        0.5373272 , 0.53815246, 0.41563308, 0.40667117, 0.65529   ,
        0.5291939 , 0.13502538, 0.59320295, 0.5388031 , 0.17635989,
        0.45555162, 0.9611225 , 0.7442961 , 0.77252376, 0.6969732 ,
        0.57887435, 0.74274695, 0.25819337, 0.2897116 , 0.10989571,
        0.6813458 , 0.7710763 , 0.7605777 , 0.5021825 , 0.03790379],
       dtype=float32)>, TensorShape([30]))

## One-hot encoding tenor

In [48]:
# Creating a list of indices
l = [0,1,2,3] 
tf.one_hot(l,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [49]:
# Specify custom values for one hot encoding
tf.one_hot(l,depth=4,on_value='python',off_value='javascript')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'python', b'javascript', b'javascript', b'javascript'],
       [b'javascript', b'python', b'javascript', b'javascript'],
       [b'javascript', b'javascript', b'python', b'javascript'],
       [b'javascript', b'javascript', b'javascript', b'python']],
      dtype=object)>

## Square,log,square root in tensor

In [56]:
# Creating a tensor using range function
S = tf.range(1,8)
S

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [55]:
# Squaring S
tf.square(S)

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([   1,   16,   81,  256,  625, 1296, 2401], dtype=int32)>

In [57]:
# square root of S
tf.sqrt(tf.cast(S,dtype=tf.float32))  #int is not supported

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512], dtype=float32)>

In [60]:
# find the log 
tf.math.log(tf.cast(S,dtype=tf.float32)) #int is not supported

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459101], dtype=float32)>

## Using Tensor with NumPy

### In creation of model we come across numpy and tensor interaction quite often!😁

In [66]:
#Creating a tensor from numpy
N = tf.constant (np.array([2.3,2.4,3.2]))
N,type(N)

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.3, 2.4, 3.2])>,
 tensorflow.python.framework.ops.EagerTensor)

In [65]:
# recreating the numpy from the tensor
np.array(N),type(np.array(N))

(array([2.3, 2.4, 3.2]), numpy.ndarray)

In [67]:
# Alternative way tensor --> numpy
N.numpy(),type(N.numpy())

(array([2.3, 2.4, 3.2]), numpy.ndarray)

In [69]:
# The default datatype of each are slightly different
numpy_N = tf.constant(np.array([2.,3.,4.]))
tensor_N = tf.constant([2.,3.,4.])
# Check the datatype of each 
numpy_N.dtype,tensor_N.dtype
# default for numpy is 64

(tf.float64, tf.float32)